export enum TagNames {
  MAIN = "main",
  SECTION = "section",
  SECTION_LABEL = "label",
  PARAGRATH = "p",
  HEADER_SECOND = "h2",
  HEADER_THIRD = "h3",
  BLOCK = "div",
  SPAN = "span",
  LIST = "ul",
  LIST_ITEM = "li",
  LINK = "a",
  BUTTON = "button",
  PRE = "pre",
  INPUT = "input",
}
